/// Synonym groups for everyday things people keep in their gallery.
///
/// Each group has ~5–7 RU+EN forms so a user typing any of them (or ML Kit
/// emitting an English label) still finds the photo. Keep groups focused:
/// short ambiguous tokens like "код", "id", "card", "pass" alone are avoided
/// because they false-positive across unrelated photos.
///
/// Tokens must be unique across all groups — the lookup map keeps only the
/// last writer for a colliding key, which silently breaks search.
class SynonymEngine {
  static const _groups = <Set<String>>[
    // ── Animals / pets ───────────────────────────────────────────────────
    {'собака', 'собаки', 'пес', 'пёс', 'щенок', 'dog', 'puppy'},
    {'кошка', 'кошки', 'кот', 'котенок', 'котёнок', 'cat', 'kitten'},
    {'животное', 'животные', 'питомец', 'зверь', 'animal', 'pet', 'creature'},
    {'птица', 'птицы', 'пернатые', 'птичка', 'bird', 'wildlife', 'fowl'},
    {'лошадь', 'лошади', 'конь', 'жеребец', 'horse', 'pony', 'equine'},
    {'рыба', 'рыбы', 'рыбка', 'аквариум', 'fish', 'aquarium', 'fishing'},
    {'кролик', 'кролики', 'зайчик', 'заяц', 'rabbit', 'bunny', 'hare'},
    {'хомяк', 'хомяки', 'хомячок', 'грызун', 'hamster', 'rodent', 'cavy'},
    {'насекомое', 'насекомые', 'бабочка', 'жук', 'insect', 'butterfly', 'bug'},
    {'корова', 'коровы', 'бык', 'тёлка', 'cow', 'cattle', 'bull'},
    {'свинья', 'свиньи', 'поросёнок', 'хрюшка', 'pig', 'piglet', 'swine'},
    {'овца', 'овцы', 'баран', 'ягнёнок', 'sheep', 'lamb', 'ram'},
    {'коза', 'козы', 'козёл', 'козлёнок', 'goat', 'kidgoat', 'billy'},
    {'курица', 'курицы', 'петух', 'цыплёнок', 'chicken', 'rooster', 'hen'},
    {'утка', 'утки', 'утёнок', 'селезень', 'duck', 'duckling', 'drake'},
    {'гусь', 'гуси', 'гусёнок', 'гусыня', 'goose', 'gosling', 'geese'},
    {'попугай', 'попугаи', 'ара', 'волнистый', 'parrot', 'budgie', 'macaw'},
    {'черепаха', 'черепахи', 'черепашка', 'turtle', 'tortoise', 'terrapin'},
    {'змея', 'змеи', 'гадюка', 'удав', 'snake', 'serpent', 'python'},
    {'ящерица', 'ящерицы', 'геккон', 'игуана', 'lizard', 'gecko', 'iguana'},
    {'мышь', 'мыши', 'мышка', 'крыса', 'mouse', 'rat', 'mice'},
    {'лиса', 'лисы', 'лисица', 'лисенок', 'fox', 'vixen', 'foxes'},
    {'медведь', 'медведи', 'мишка', 'медвежонок', 'bear', 'cub', 'grizzly'},
    {'волк', 'волки', 'волчица', 'волчонок', 'wolf', 'wolves', 'lupine'},
    {'олень', 'олени', 'лань', 'оленёнок', 'deer', 'stag', 'doe'},
    {'слон', 'слоны', 'слонёнок', 'хобот', 'elephant', 'trunk', 'pachyderm'},
    {'жираф', 'жирафы', 'жирафик', 'giraffe', 'giraffes', 'tallneck'},
    {'тигр', 'тигры', 'тигрёнок', 'tiger', 'tigers', 'tigress'},
    {'лев', 'львы', 'львица', 'львёнок', 'lion', 'lions', 'lioness'},
    {
      'обезьяна',
      'обезьяны',
      'мартышка',
      'шимпанзе',
      'monkey',
      'ape',
      'primate',
    },
    {'пингвин', 'пингвины', 'пингвинёнок', 'penguin', 'penguins', 'tuxedo'},
    {'дельфин', 'дельфины', 'касатка', 'dolphin', 'orca', 'porpoise'},
    {'кит', 'киты', 'китёнок', 'whale', 'whales', 'cetacean'},
    {'паук', 'пауки', 'паутина', 'spider', 'arachnid', 'web'},
    {'пчела', 'пчёлы', 'пчелы', 'шмель', 'bee', 'bees', 'bumblebee'},
    {'муравей', 'муравьи', 'муравейник', 'ant', 'ants', 'anthill'},

    // ── Transport ────────────────────────────────────────────────────────
    {'машина', 'машины', 'авто', 'автомобиль', 'тачка', 'car', 'vehicle'},
    {
      'мотоцикл',
      'мотоциклы',
      'байк',
      'мопед',
      'motorcycle',
      'motorbike',
      'scooter',
    },
    {'велосипед', 'велосипеды', 'велик', 'bike', 'bicycle', 'cycling', 'cycle'},
    {'автобус', 'автобусы', 'маршрутка', 'bus', 'coach', 'shuttle'},
    {'поезд', 'поезда', 'электричка', 'метро', 'train', 'metro', 'subway'},
    {'самолёт', 'самолет', 'самолёты', 'авиа', 'airplane', 'aircraft', 'plane'},
    {'корабль', 'корабли', 'лодка', 'яхта', 'ship', 'boat', 'yacht'},
    {'грузовик', 'грузовики', 'фура', 'тягач', 'truck', 'lorry', 'semi'},
    {'такси', 'кабина', 'uber', 'яндекстакси', 'taxi', 'cab', 'rideshare'},
    {
      'трамвай',
      'трамваи',
      'троллейбус',
      'трамвайный',
      'tram',
      'streetcar',
      'trolley',
    },
    {
      'вертолёт',
      'вертолет',
      'вертолёты',
      'helicopter',
      'chopper',
      'heli',
      'rotor',
    },
    {
      'самокат',
      'самокаты',
      'кикшеринг',
      'kickshare',
      'kickscooter',
      'есамокат',
      'escoop',
    },
    {'парковка', 'паркинги', 'стоянка', 'parking', 'garage', 'carpark', 'lot'},
    {'заправка', 'заправки', 'азс', 'бензин', 'gasstation', 'petrol', 'fuel'},
    {
      'номерной',
      'госномер',
      'номеравто',
      'licenseplate',
      'numberplate',
      'автономер',
      'регистрация',
    },

    // ── Documents / money / IDs ───────────────────────────────────────────
    {'ikea', 'икеа', 'икея', 'икею', 'икеи', 'икее', 'икеевский'},
    {'чек', 'чеки', 'квитанция', 'счет', 'receipt', 'invoice', 'bill'},
    {
      'документ',
      'документы',
      'бумага',
      'справка',
      'document',
      'paperwork',
      'certificate',
      'бумажка',
      'бумажки',
    },
    {
      'паспорт',
      'загранпаспорт',
      'passport',
      'удостоверение',
      'паспортные',
      'identification',
      'паспорта',
    },
    {
      'права',
      'водительские',
      'водительское',
      'license',
      'licence',
      'driving',
      'водитель',
      'водительских',
    },
    {'билет', 'билеты', 'посадочный', 'пропуск', 'ticket', 'boarding', 'stub'},
    {
      'визитка',
      'визитки',
      'визитная',
      'businesscard',
      'namecard',
      'визитк',
      'визитку',
    },
    {
      'пароль',
      'пароли',
      'логин',
      'login',
      'password',
      'passcode',
      'пинкод',
    },
    {'деньги', 'купюра', 'купюры', 'наличные', 'cash', 'money', 'currency'},
    {
      'банковская',
      'пластик',
      'visa',
      'mastercard',
      'bankcard',
      'creditcard',
      'debit',
    },
    {
      'кошелёк',
      'кошелек',
      'портмоне',
      'бумажник',
      'wallet',
      'purse',
      'billfold',
    },
    {
      'договор',
      'договоры',
      'контракт',
      'соглашение',
      'contract',
      'agreement',
      'deal',
    },
    {
      'диплом',
      'дипломы',
      'аттестат',
      'сертификат',
      'diploma',
      'degree',
      'cert',
    },
    {
      'страховка',
      'полис',
      'страховки',
      'insurance',
      'policy',
      'страхов',
      'осаго',
    },
    {
      'рецепт',
      'рецепты',
      'назначение',
      'prescription',
      'rx',
      'медицинский',
      'аптека',
    },
    {
      'гарантия',
      'гарантии',
      'гарантийный',
      'warranty',
      'гарантийка',
      'гарант',
    },
    {'снилс', 'инн', 'омс', 'налоговая', 'taxid', 'insurancecard', 'соцкарта'},
    {
      'квитанцияжкх',
      'коммуналка',
      'жкх',
      'квартплата',
      'utility',
      'utilities',
      'rentbill',
    },
    {'резюме', 'cv', 'анкета', 'вакансия', 'resume', 'curriculum', 'jobapp'},
    {
      'перевод',
      'переводы',
      'квиток',
      'банковский',
      'transfer',
      'bankwire',
      'payment',
    },
    {'акция', 'акции', 'скидка', 'промокод', 'discount', 'promo', 'coupon'},

    // ── Screens / codes ──────────────────────────────────────────────────
    {'скриншот', 'скриншоты', 'снимок', 'screenshot', 'screencap', 'capture'},
    {'qr', 'qr-код', 'qrкод', 'сканирование', 'barcode', 'qrcode', 'штрихкод'},
    {
      'чаты',
      'переписка',
      'сообщение',
      'сообщения',
      'chat',
      'message',
      'messenger',
    },
    {'whatsapp', 'ватсап', 'телеграм', 'telegram', 'viber', 'imessage', 'sms'},
    {
      'инстаграм',
      'instagram',
      'сторис',
      'stories',
      'тикток',
      'tiktok',
      'reels',
    },

    // ── People ───────────────────────────────────────────────────────────
    {
      'человек',
      'люди',
      'лицо',
      'портрет',
      'person',
      'people',
      'human',
      'face',
      'portrait',
    },
    {'мужчина', 'мужчины', 'парень', 'мужик', 'man', 'male', 'guy'},
    {'женщина', 'женщины', 'девушка', 'девочка', 'woman', 'female', 'girl'},
    {
      'ребёнок',
      'ребенок',
      'дети',
      'малыш',
      'сын',
      'дочь',
      'дочка',
      'сынок',
      'child',
      'baby',
      'kid',
    },
    {
      'семья',
      'семейное',
      'семейный',
      'родственники',
      'family',
      'relatives',
      'родные',
    },
    {'селфи', 'селфишка', 'автопортрет', 'selfie', 'selfportrait', 'autophoto'},
    {'свадьба', 'свадебное', 'жених', 'невеста', 'wedding', 'bride', 'groom'},
    {
      'деньрождение',
      'др',
      'именины',
      'birthday',
      'bday',
      'празднование',
      'торжество',
    },
    {
      'бабушка',
      'бабули',
      'бабулька',
      'бабуся',
      'grandmother',
      'grandma',
      'granny',
    },
    {
      'дедушка',
      'дедули',
      'дедушкая',
      'дед',
      'grandfather',
      'grandpa',
      'granddad',
    },
    {'мама', 'мамы', 'мать', 'мамочка', 'mother', 'mom', 'mommy'},
    {'папа', 'папы', 'отец', 'папочка', 'father', 'dad', 'daddy'},
    {'друзья', 'друг', 'подруга', 'компания', 'friends', 'friend', 'buddy'},
    {
      'пара',
      'парочка',
      'влюблённые',
      'влюбленные',
      'couple',
      'lovers',
      'partners',
    },
    {
      'беременность',
      'беременная',
      'животик',
      'pregnancy',
      'pregnant',
      'bump',
      'maternity',
    },
    {
      'выпускной',
      'выпускники',
      'выпускница',
      'graduation',
      'graduate',
      'prom',
      'выпускнойбал',
    },
    {
      'команда',
      'коллеги',
      'сотрудники',
      'team',
      'colleagues',
      'coworkers',
      'staff',
    },

    // ── Food & drink ─────────────────────────────────────────────────────
    {'еда', 'блюдо', 'пища', 'едашка', 'food', 'meal', 'dish'},
    {'пицца', 'пиццы', 'пиццерия', 'pizza', 'pizzas', 'pepperoni', 'пепперони'},
    {
      'бургер',
      'бургеры',
      'гамбургер',
      'burger',
      'hamburger',
      'cheeseburger',
      'fastfood',
    },
    {'суши', 'роллы', 'сашими', 'sushi', 'rolls', 'sashimi', 'японская'},
    {'торт', 'торты', 'пирожное', 'десерт', 'cake', 'dessert', 'pastry'},
    {'хлеб', 'булка', 'выпечка', 'батон', 'bread', 'bakery', 'loaf'},
    {'фрукты', 'фрукт', 'яблоко', 'банан', 'fruit', 'apple', 'banana'},
    {'овощи', 'овощ', 'салат', 'помидор', 'vegetable', 'salad', 'veggies'},
    {
      'мороженое',
      'мороженого',
      'пломбир',
      'ice cream',
      'icecream',
      'gelato',
      'сорбет',
    },
    {
      'кофе',
      'капучино',
      'эспрессо',
      'латте',
      'coffee',
      'cappuccino',
      'espresso',
    },
    {'чай', 'чаепитие', 'заварка', 'чайник', 'tea', 'teapot', 'chai'},
    {'вино', 'шампанское', 'бокал', 'виноград', 'wine', 'champagne', 'vino'},
    {'пиво', 'пивка', 'кружка', 'лагер', 'beer', 'ale', 'brew'},
    {
      'завтрак',
      'завтраки',
      'утренний',
      'breakfast',
      'brunch',
      'утро',
      'morning',
    },
    {'обед', 'обеды', 'ланч', 'lunch', 'midday', 'полуденный', 'дневной'},
    {'ужин', 'ужины', 'вечерний', 'dinner', 'supper', 'вечер', 'evening'},
    {'ресторан', 'кафе', 'столовая', 'бистро', 'restaurant', 'cafe', 'bistro'},
    {'суп', 'супы', 'борщ', 'бульон', 'soup', 'broth', 'chowder'},
    {'паста', 'макароны', 'спагетти', 'лапша', 'pasta', 'spaghetti', 'noodles'},
    {'стейк', 'стейки', 'мясо', 'шашлык', 'steak', 'meat', 'bbq'},
    {
      'курицаеда',
      'цыплёнокеда',
      'куриное',
      'grillchicken',
      'friedchicken',
      'roastchicken',
      'poultry',
    },
    {
      'рыбаеда',
      'морепродукты',
      'креветки',
      'seafood',
      'shrimp',
      'salmon',
      'лосось',
    },
    {'сыр', 'сыры', 'сырный', 'cheese', 'cheddar', 'mozarella', 'моцарелла'},
    {'яйцо', 'яйца', 'яичница', 'омлет', 'egg', 'eggs', 'omelette'},
    {
      'шоколад',
      'конфеты',
      'сладости',
      'chocolate',
      'candy',
      'sweets',
      'шоколадка',
    },
    {
      'печенье',
      'печенья',
      'печеньки',
      'cookie',
      'cookies',
      'biscuit',
      'бисквит',
    },
    {'пиццароллы', 'shawarma', 'шаурма', 'шаверма', 'донер', 'doner', 'kebab'},
    {'сок', 'соки', 'фреш', 'смузи', 'juice', 'smoothie', 'fresh'},
    {'вода', 'водичка', 'минералка', 'бутылка', 'water', 'bottle', 'mineral'},
    {
      'коктейль',
      'коктейли',
      'милкшейк',
      'cocktail',
      'milkshake',
      'shake',
      'мохито',
    },
    {
      'пиццадоставка',
      'доставкаеды',
      'едадоставка',
      'delivery',
      'takeout',
      'takeaway',
      'упаковкаеды',
    },

    // ── Plants / nature ──────────────────────────────────────────────────
    {
      'растение',
      'растения',
      'цветок',
      'цветы',
      'дерево',
      'деревья',
      'plant',
      'flower',
      'tree',
    },
    {'лес', 'роща', 'чаща', 'чащоба', 'forest', 'woods', 'woodland'},
    {'парк', 'парки', 'сквер', 'сад', 'park', 'garden', 'plaza'},
    {'море', 'океан', 'пляж', 'побережье', 'sea', 'ocean', 'beach'},
    {'озеро', 'озёра', 'озера', 'пруд', 'lake', 'pond', 'lagoon'},
    {'река', 'реки', 'ручей', 'водопад', 'river', 'stream', 'waterfall'},
    {'гора', 'горы', 'холм', 'вершина', 'mountain', 'hill', 'peak'},
    {'закат', 'закаты', 'рассвет', 'солнце', 'sunset', 'sunrise', 'sun'},
    {'небо', 'облака', 'тучи', 'небосвод', 'sky', 'cloud', 'clouds'},
    {'снег', 'снежок', 'сугроб', 'метель', 'snow', 'snowfall', 'blizzard'},
    {'дождь', 'ливень', 'лужа', 'зонтик', 'rain', 'rainfall', 'umbrella'},
    {'ночь', 'ночной', 'луна', 'звёзды', 'night', 'moon', 'stars'},
    {'роза', 'розы', 'букет', 'букеты', 'rose', 'roses', 'bouquet'},
    {'кактус', 'кактусы', 'суккулент', 'cactus', 'succulent', 'aloe', 'алоэ'},
    {'трава', 'газон', 'лужайка', 'поле', 'grass', 'lawn', 'meadow'},
    {'камень', 'камни', 'скала', 'утес', 'stone', 'rock', 'cliff'},
    {'песок', 'песчаный', 'дюна', 'дюны', 'sand', 'dune', 'sandy'},
    {'туман', 'туманный', 'дымка', 'мгла', 'fog', 'mist', 'haze'},
    {'радуга', 'радуги', 'радужный', 'rainbow', 'spectrum', 'arc', 'радуг'},
    {'гроза', 'молния', 'гром', 'шторм', 'storm', 'thunder', 'lightning'},
    {'осень', 'осенний', 'листва', 'autumn', 'fall', 'leaves', 'foliage'},
    {'зима', 'зимний', 'мороз', 'winter', 'frost', 'icy', 'холод'},
    {'весна', 'весенний', 'цветение', 'spring', 'bloom', 'blossom', 'расцвет'},
    {'лето', 'летний', 'жара', 'summer', 'heat', 'sunny', 'зной'},

    // ── Places / travel ──────────────────────────────────────────────────
    {'город', 'города', 'городской', 'мегаполис', 'city', 'urban', 'downtown'},
    {'улица', 'улицы', 'проспект', 'дорога', 'street', 'road', 'avenue'},
    {'дом', 'дома', 'здание', 'постройка', 'house', 'building', 'home'},
    {
      'квартира',
      'квартиры',
      'апартаменты',
      'жильё',
      'apartment',
      'flat',
      'condo',
    },
    {'отель', 'гостиница', 'хостел', 'номер', 'hotel', 'hostel', 'inn'},
    {
      'аэропорт',
      'аэропорты',
      'терминал',
      'вылет',
      'airport',
      'terminal',
      'departure',
    },
    {
      'вокзал',
      'станция',
      'платформа',
      'перрон',
      'station',
      'platform',
      'railstation',
    },
    {'магазин', 'магазины', 'шопинг', 'торговый', 'shop', 'store', 'mall'},
    {
      'отпуск',
      'отпуска',
      'путешествие',
      'поездка',
      'vacation',
      'travel',
      'trip',
    },
    {'карта', 'карты', 'маршрут', 'навигация', 'map', 'route', 'gps'},
    {
      'музей',
      'музеи',
      'выставка',
      'галерея',
      'museum',
      'exhibition',
      'gallery',
    },
    {'церковь', 'храм', 'собор', 'мечеть', 'church', 'temple', 'mosque'},
    {
      'мост',
      'мосты',
      'путепровод',
      'bridge',
      'overpass',
      'viaduct',
      'crossing',
    },
    {
      'фонтан',
      'фонтаны',
      'фонтанчик',
      'fountain',
      'fountains',
      'spray',
      'бассейнчик',
    },
    {
      'памятник',
      'памятники',
      'статуя',
      'монумент',
      'monument',
      'statue',
      'memorial',
    },
    {'деревня', 'село', 'дача', 'посёлок', 'village', 'countryside', 'cottage'},
    {
      'башня',
      'башни',
      'небоскрёб',
      'небоскреб',
      'tower',
      'skyscraper',
      'высотка',
    },
    {'рынок', 'рынки', 'базар', 'ярмарка', 'market', 'bazaar', 'fair'},
    {'бар', 'бары', 'паб', 'клуб', 'bar', 'pub', 'nightclub'},
    {
      'библиотека',
      'библиотеки',
      'читальня',
      'library',
      'libraries',
      'readingroom',
      'архив',
    },
    {
      'стадион',
      'стадионы',
      'арена',
      'трибуна',
      'stadium',
      'arena',
      'bleachers',
    },
    {'зоопарк', 'зоопарки', 'зоо', 'zoo', 'zoos', 'wildlifepark', 'зверинец'},
    {
      'аквапарк',
      'аквапарки',
      'водныйпарк',
      'waterpark',
      'waterslide',
      'аква',
      'горкиводные',
    },
    {'цирк', 'цирки', 'цирковой', 'circus', 'circusact', 'аренацирка', 'клоун'},

    // ── Home / interiors ─────────────────────────────────────────────────
    {
      'комната',
      'комнаты',
      'интерьер',
      'помещение',
      'room',
      'interior',
      'space',
    },
    {'кухня', 'кухни', 'кухонный', 'плита', 'kitchen', 'cooker', 'stove'},
    {'спальня', 'спальни', 'кровать', 'постель', 'bedroom', 'bed', 'mattress'},
    {'ванная', 'ванна', 'душ', 'туалет', 'bathroom', 'shower', 'toilet'},
    {'мебель', 'диван', 'стол', 'стул', 'furniture', 'sofa', 'table'},
    {'ключи', 'ключ', 'связка', 'замок', 'keys', 'key', 'lock'},
    {
      'окно',
      'окна',
      'подоконник',
      'форточка',
      'window',
      'windowsill',
      'windows',
    },
    {'дверь', 'двери', 'дверной', 'порог', 'door', 'doors', 'doorway'},
    {'балкон', 'балконы', 'лоджия', 'терраса', 'balcony', 'terrace', 'patio'},
    {'шкаф', 'шкафы', 'гардероб', 'полка', 'wardrobe', 'closet', 'shelf'},
    {
      'зеркало',
      'зеркала',
      'зеркальце',
      'mirror',
      'mirrors',
      'reflection',
      'отражение',
    },
    {'лампа', 'лампы', 'люстра', 'светильник', 'lamp', 'chandelier', 'light'},
    {'ковёр', 'ковер', 'ковры', 'коврик', 'carpet', 'rug', 'mat'},
    {'шторы', 'занавески', 'тюль', 'жалюзи', 'curtains', 'blinds', 'drapes'},
    {
      'ремонт',
      'ремонты',
      'стройка',
      'отделка',
      'renovation',
      'construction',
      'remodel',
    },
    {'посуда', 'тарелка', 'чашка', 'вилка', 'dishes', 'plate', 'cup'},
    {
      'холодильник',
      'холодильники',
      'морозилка',
      'fridge',
      'refrigerator',
      'freezer',
      'холодильн',
    },
    {
      'стиралка',
      'стиральная',
      'стирка',
      'washer',
      'washingmachine',
      'laundry',
      'прачечная',
    },
    {
      'пылесос',
      'пылесосы',
      'уборка',
      'vacuum',
      'cleaner',
      'hoover',
      'cleaning',
    },

    // ── Electronics / gadgets ────────────────────────────────────────────
    {
      'телефон',
      'телефоны',
      'смартфон',
      'айфон',
      'phone',
      'smartphone',
      'iphone',
    },
    {
      'ноутбук',
      'ноутбуки',
      'лэптоп',
      'компьютер',
      'laptop',
      'notebook',
      'computer',
    },
    {
      'наушники',
      'наушник',
      'гарнитура',
      'airpods',
      'headphones',
      'earbuds',
      'headset',
    },
    {
      'часы',
      'часики',
      'наручные',
      'smartwatch',
      'watch',
      'wristwatch',
      'clock',
    },
    {'камера', 'камеры', 'фотоаппарат', 'объектив', 'camera', 'lens', 'dslr'},
    {'телевизор', 'тв', 'экран', 'монитор', 'tv', 'television', 'monitor'},
    {
      'зарядка',
      'зарядки',
      'кабель',
      'шнур',
      'charger',
      'cable',
      'chargingcable',
    },
    {'планшет', 'планшеты', 'айпад', 'tablet', 'ipad', 'tab', 'планшетный'},
    {
      'клавиатура',
      'клавиатуры',
      'клавиши',
      'keyboard',
      'keyboards',
      'keysboard',
      'клава',
    },
    {
      'мышкакомп',
      'компьютернаямышь',
      'тачпад',
      'mousepc',
      'trackpad',
      'pointer',
      'курсор',
    },
    {
      'колонка',
      'колонки',
      'динамик',
      'speaker',
      'speakers',
      'bluetooth',
      'саундбар',
    },
    {
      'принтер',
      'принтеры',
      'печать',
      'printer',
      'printing',
      'сканер',
      'scanner',
    },
    {'роутер', 'роутеры', 'вайфай', 'вайфая', 'вайфаю', 'router', 'wifi', 'modem', 'интернет'},
    {
      'батарея',
      'батареи',
      'аккумулятор',
      'battery',
      'powerbank',
      'заряд',
      'power',
    },
    {
      'геймпад',
      'джойстик',
      'контроллер',
      'gamepad',
      'joystick',
      'controller',
      'xbox',
    },
    {
      'приставка',
      'playstation',
      'nintendo',
      'консоль',
      'console',
      'ps5',
      'gaming',
    },
    {'дрон', 'дроны', 'квадрокоптер', 'drone', 'drones', 'quadcopter', 'uav'},

    // ── Clothes / accessories ────────────────────────────────────────────
    {'одежда', 'вещи', 'наряд', 'гардеробный', 'clothes', 'clothing', 'outfit'},
    {'обувь', 'кроссовки', 'туфли', 'ботинки', 'shoes', 'sneakers', 'boots'},
    {'платье', 'платья', 'сарафан', 'платьице', 'dress', 'gown', 'frock'},
    {'куртка', 'куртки', 'пальто', 'пуховик', 'jacket', 'coat', 'parka'},
    {'сумка', 'сумки', 'рюкзак', 'пакет', 'bag', 'backpack', 'handbag'},
    {'очки', 'очков', 'солнечные', 'линзы', 'glasses', 'sunglasses', 'eyewear'},
    {
      'украшения',
      'кольцо',
      'серьги',
      'цепочка',
      'jewelry',
      'jewellery',
      'ring',
    },
    {'футболка', 'футболки', 'майка', 'тишка', 'tshirt', 'tee', 'shirt'},
    {'джинсы', 'джинсов', 'брюки', 'штаны', 'jeans', 'pants', 'trousers'},
    {'шапка', 'шапки', 'кепка', 'шляпа', 'hat', 'cap', 'beanie'},
    {'шарф', 'шарфы', 'снуд', 'платок', 'scarf', 'shawl', 'wrap'},
    {
      'перчатки',
      'перчатка',
      'варежки',
      'gloves',
      'mittens',
      'gauntlets',
      'рукавицы',
    },
    {'носки', 'носок', 'гольфы', 'socks', 'stockings', 'hosiery', 'колготки'},
    {
      'купальник',
      'купальники',
      'плавки',
      'swimsuit',
      'bikini',
      'swimwear',
      'бикини',
    },
    {
      'галстук',
      'галстуки',
      'бабочкагалстук',
      'tie',
      'necktie',
      'bowtie',
      'галстучок',
    },
    {'ремень', 'ремни', 'пояс', 'belt', 'belts', 'strap', 'поясок'},
    {
      'часыукрашение',
      'браслет',
      'браслеты',
      'bracelet',
      'bracelets',
      'bangle',
      'wristband',
    },
    {'ожерелье', 'бусы', 'кулон', 'necklace', 'pendant', 'beads', 'чокер'},

    // ── Health / medicine / body ─────────────────────────────────────────
    {
      'лекарство',
      'лекарства',
      'таблетки',
      'пилюли',
      'medicine',
      'pills',
      'medication',
    },
    {'больница', 'больницы', 'клиника', 'врач', 'hospital', 'clinic', 'doctor'},
    {'анализ', 'анализы', 'результат', 'лаборатория', 'lab', 'test', 'results'},
    {
      'температура',
      'градусник',
      'термометр',
      'temperature',
      'thermometer',
      'fever',
      'жар',
    },
    {'маска', 'маски', 'медицинская', 'mask', 'facemask', 'ppe', 'респиратор'},
    {
      'прививка',
      'прививки',
      'вакцина',
      'vaccine',
      'vaccination',
      'shot',
      'укол',
    },
    {'зубы', 'зуб', 'стоматолог', 'teeth', 'tooth', 'dentist', 'улыбка'},
    {
      'волосы',
      'причёска',
      'прическа',
      'стрижка',
      'hair',
      'hairstyle',
      'haircut',
    },
    {
      'макияж',
      'мейкап',
      'косметика',
      'makeup',
      'cosmetics',
      'lipstick',
      'помада',
    },
    {
      'спортзал',
      'тренажёр',
      'тренажер',
      'гантели',
      'workout',
      'dumbbell',
      'weights',
    },

    // ── Work / school / notes ────────────────────────────────────────────
    {'работа', 'офис', 'офисный', 'рабочий', 'work', 'office', 'workplace'},
    {'школа', 'школы', 'класс', 'урок', 'school', 'classroom', 'lesson'},
    {
      'университет',
      'универ',
      'институт',
      'вуз',
      'university',
      'college',
      'campus',
    },
    {
      'заметка',
      'заметки',
      'записка',
      'рукопись',
      'note',
      'memo',
      'handwriting',
    },
    {'книга', 'книги', 'учебник', 'журнал', 'book', 'textbook', 'magazine'},
    {
      'презентация',
      'слайд',
      'слайды',
      'доклад',
      'presentation',
      'slides',
      'deck',
    },
    {'письмо', 'письма', 'конверт', 'почта', 'letter', 'mail', 'envelope'},
    {'посылка', 'посылки', 'коробка', 'доставка', 'package', 'parcel', 'box'},
    {
      'доска',
      'маркерная',
      'флипчарт',
      'whiteboard',
      'blackboard',
      'flipchart',
      'меловая',
    },
    {
      'календарь',
      'календари',
      'расписание',
      'calendar',
      'schedule',
      'planner',
      'дата',
    },
    {'ручка', 'ручки', 'карандаш', 'маркер', 'pen', 'pencil', 'marker'},
    {
      'тетрадь',
      'тетради',
      'блокнот',
      'notebookpaper',
      'notepad',
      'workbook',
      'записная',
    },
    {
      'дипломный',
      'курсовая',
      'экзамен',
      'exam',
      'thesis',
      'coursework',
      'дипломная',
    },
    {'совещание', 'митинг', 'встреча', 'meeting', 'conference', 'call', 'zoom'},

    // ── Leisure / sport / events ─────────────────────────────────────────
    {'спорт', 'тренировка', 'зал', 'фитнес', 'sport', 'gym', 'fitness'},
    {'футбол', 'футбольный', 'мяч', 'гол', 'football', 'soccer', 'ball'},
    {'бег', 'пробежка', 'марафон', 'кросс', 'running', 'jogging', 'marathon'},
    {'плавание', 'бассейн', 'заплыв', 'купание', 'swimming', 'pool', 'swim'},
    {'концерт', 'концерты', 'сцена', 'выступление', 'concert', 'stage', 'gig'},
    {'кино', 'фильм', 'кинотеатр', 'сеанс', 'cinema', 'movie', 'film'},
    {'театр', 'спектакль', 'пьеса', 'афиша', 'theater', 'theatre', 'play'},
    {'музыка', 'песня', 'мелодия', 'гитара', 'music', 'song', 'guitar'},
    {
      'праздник',
      'праздники',
      'вечеринка',
      'тусовка',
      'party',
      'celebration',
      'fest',
    },
    {'новыйгод', 'ёлка', 'елка', 'рождество', 'christmas', 'newyear', 'xmas'},
    {
      'подарок',
      'подарки',
      'сюрприз',
      'упаковка',
      'gift',
      'present',
      'surprise',
    },
    {'игрушка', 'игрушки', 'игрушками', 'мягкая', 'toy', 'toys', 'plush'},
    {
      'баскетбол',
      'баскетбольный',
      'кольцобаскет',
      'basketball',
      'hoop',
      'nba',
      'баскет',
    },
    {'теннис', 'теннисный', 'ракетка', 'tennis', 'racket', 'court', 'корт'},
    {'хоккей', 'хоккейный', 'шайба', 'hockey', 'puck', 'icehockey', 'клюшка'},
    {'йога', 'йоги', 'растяжка', 'yoga', 'stretch', 'pilates', 'пилатес'},
    {'танцы', 'танец', 'танцпол', 'dance', 'dancing', 'ballet', 'балет'},
    {'лыжи', 'лыжный', 'сноуборд', 'ski', 'skiing', 'snowboard', 'горныелыжи'},
    {
      'велосипедспорт',
      'велопрогулка',
      'велоспорт',
      'biking',
      'ride',
      'вело',
      'велосипедист',
    },
    {'рыбалка', 'рыбалки', 'удочка', 'fishingrod', 'angler', 'catch', 'улов'},
    {'охота', 'охоты', 'охотник', 'hunting', 'hunter', 'hunt', 'дичь'},
    {'пикник', 'пикники', 'шашлыки', 'picnic', 'cookout', 'outdoor', 'костёр'},
    {'поход', 'походы', 'туризм', 'hiking', 'trek', 'camping', 'кемпинг'},
    {'игра', 'игры', 'настолка', 'game', 'games', 'boardgame', 'настольная'},
    {'пазл', 'пазлы', 'головоломка', 'puzzle', 'jigsaw', 'riddle', 'пазллы'},
    {
      'фортепиано',
      'пианино',
      'рояль',
      'piano',
      'keyboardpiano',
      'pianokeys',
      'клавишифорте',
    },
    {
      'барабаны',
      'ударные',
      'барабан',
      'drums',
      'drum',
      'percussion',
      'drumkit',
    },
    {'скрипка', 'скрипки', 'виолончель', 'violin', 'cello', 'fiddle', 'смычок'},
    {
      'фестиваль',
      'фестивали',
      'фест',
      'festival',
      'festivals',
      'festivity',
      'ярмаркафест',
    },
    {
      'карнавал',
      'карнавалы',
      'маскарад',
      'carnival',
      'masquerade',
      'parade',
      'парад',
    },
    {
      'halloween',
      'хэллоуин',
      'тыква',
      'pumpkin',
      'spooky',
      'костюм',
      'costume',
    },
    {
      'валентин',
      'валентинка',
      '14февраля',
      'valentine',
      'valentines',
      'hearts',
      'сердечки',
    },
    {
      'пасха',
      'пасхи',
      'яйцапасха',
      'easter',
      'easteregg',
      'кулич',
      'пасхальный',
    },

    // ── Misc everyday objects ────────────────────────────────────────────
    {
      'зонт',
      'зонты',
      'зонтикдождь',
      'umbrellaopen',
      'parasol',
      'дождевик',
      'raincoat',
    },
    {'огонь', 'костёркостёр', 'камин', 'fire', 'fireplace', 'flame', 'пламя'},
    {
      'свеча',
      'свечи',
      'подсвечник',
      'candle',
      'candles',
      'candlestick',
      'свечка',
    },
    {'флаг', 'флаги', 'знамя', 'flag', 'flags', 'banner', 'стяг'},
    {
      'картаигральная',
      'колода',
      'покер',
      'playingcards',
      'poker',
      'deckcards',
      'картыигра',
    },
    {'деньгимонеты', 'монета', 'монеты', 'coin', 'coins', 'change', 'мелочь'},
    {
      'инструмент',
      'инструменты',
      'отвёртка',
      'tool',
      'tools',
      'screwdriver',
      'молоток',
    },
    {
      'велосипедзамок',
      'замоквело',
      'цепь',
      'bikelock',
      'chain',
      'padlock',
      'навесной',
    },
    {'мусор', 'мусорка', 'урна', 'trash', 'garbage', 'bin', 'отходы'},
    {
      'сигнал',
      'светофор',
      'дорожныйзнак',
      'trafficlight',
      'sign',
      'roadsign',
      'знак',
    },
    {
      'граффити',
      'граффитистена',
      'стритart',
      'graffiti',
      'streetart',
      'mural',
      'роспись',
    },
    {'тату', 'татуировка', 'татуировки', 'tattoo', 'tattoos', 'ink', 'татуха'},
    {'питомецфото', 'лапы', 'лапка', 'paws', 'paw', 'хвост', 'tail'},
  ];

  late final Map<String, Set<String>> _lookup = () {
    final map = <String, Set<String>>{};
    for (final group in _groups) {
      final normalizedGroup = {for (final token in group) normalize(token)};
      for (final token in normalizedGroup) {
        map[token] = normalizedGroup;
      }
    }
    return map;
  }();

  /// Gendered / age people queries ("девушка", "мужчина", "ребёнок") live in
  /// their own synonym groups so they don't collapse into each other. Face
  /// indexing only stores the core people tokens (person/face/люди), so without
  /// this bridge "девушка" would miss every face-detected photo.
  static const _peopleCore = {
    'человек',
    'люди',
    'лицо',
    'портрет',
    'person',
    'people',
    'human',
    'face',
    'portrait',
  };

  static const _peopleSearchBridge = {
    'девушка',
    'женщина',
    'женщины',
    'девочка',
    'woman',
    'female',
    'girl',
    'мужчина',
    'мужчины',
    'парень',
    'мужик',
    'man',
    'male',
    'guy',
    'ребенок',
    'ребёнок',
    'дети',
    'малыш',
    'child',
    'baby',
    'kid',
    'семья',
    'семейное',
    'семейный',
    'родственники',
    'family',
    'selfie',
    'селфи',
  };

  /// Intent bridges connect real-world concepts that are frequently indexed
  /// under different visible terms. They are intentionally narrow to avoid
  /// turning a generic semantic request into unrelated gallery noise.
  static const _intentBridges = <String, Set<String>>{
    'ikea': {'икеа', 'икея', 'мебель', 'furniture', 'магазин', 'store'},
    'икеа': {'ikea', 'икея', 'мебель', 'furniture', 'магазин', 'store'},
    'икея': {'ikea', 'икеа', 'мебель', 'furniture', 'магазин', 'store'},
    'wifi': {'вайфай', 'роутер', 'router', 'ssid', 'wpa', 'password', 'пароль'},
    'вайфай': {'wifi', 'роутер', 'router', 'ssid', 'wpa', 'password', 'пароль'},
    'пароль': {'password', 'wifi', 'вайфай', 'ssid', 'wpa', 'ключ'},
    'password': {'пароль', 'wifi', 'вайфай', 'ssid', 'wpa', 'ключ'},
    'аэропорт': {
      'airport',
      'терминал',
      'terminal',
      'самолет',
      'самолёт',
      'plane',
    },
    'airport': {
      'аэропорт',
      'терминал',
      'terminal',
      'самолет',
      'самолёт',
      'plane',
    },
    'самолет': {'самолёт', 'airplane', 'plane', 'аэропорт', 'airport'},
    'самолёт': {'самолет', 'airplane', 'plane', 'аэропорт', 'airport'},
    'plane': {'airplane', 'самолет', 'самолёт', 'аэропорт', 'airport'},
  };

  Set<String> expand(Iterable<String> tokens) {
    final expanded = <String>{};
    for (final raw in tokens) {
      final token = normalize(raw);
      if (token.isEmpty) continue;
      expanded.add(token);
      expanded.addAll(_lookup[token] ?? const {});
      if (_peopleSearchBridge.contains(token) || _peopleCore.contains(token)) {
        expanded.addAll(_peopleCore);
      }
      expanded.addAll(_intentBridges[token] ?? const {});
    }
    return expanded;
  }

  String normalize(String value) {
    return value
        .trim()
        .toLowerCase()
        .replaceAll('ё', 'е')
        .replaceAll(RegExp(r'\s+'), ' ');
  }
}
